### PR TITLE
bump version number for obspy 1.1.0 compatibility

### PR DESCRIPTION
**Pull request by megies**
When compatibility with obspy 1.1.0 is confirmed we should bump the version number.

### CODE REVIEW

**Comment by krischer** [comment]
Sounds good :-) A very minimal test might also be kind of interesting...

**Comment by megies** [comment]
Huh.. didn't know there was no tests.. ;-)

**Comment by megies** [comment]
Also, on the master branch we should add suffix `.post0` to the version number, ideally. But let's do this after this PR.

**Comment by krischer** [comment]
or just use the obspy way of versioning things. Its nice and always work.

**Comment by megies** [comment]
Yeah, either way of cleaner versioning is fine..

**Pull request merged**
