### PR TITLE
Use preferred magnitude. Set magnitude to 0.0 when not available

### PR DESCRIPTION
**Pull request by ogalanis**
Use the preferred magnitude instead of the first magnitude in the list of magnitudes. When there is no preferred magnitude or no magnitudes at all, set magnitude=0.0.

This covers more situations than the original. Setting magnitude=0.0 agrees with the hypoDD2 manual, but makes an M=0.0 ambiguous (can be the actual magnitude, or there is no magnitude available).

### CODE REVIEW

**Comment by megies** [comment]
@ogalanis this repo isn't maintained anymore, if you're interested and want to work on it, maybe we could think about moving it to some organizational account

**Comment by ogalanis** [comment]
@megies Normally I would hesitate, but since it's not maintained anyway, why not? Maybe now it's a good time since I'm still using it but my branches haven't diverged too much. How would you suggest I proceed?

**Comment by krischer** [comment]
Hi @ogalanis and @megies,

it would be great to move this repository somewhere else and maybe it has a chance to live on. I'd be happy to transfer it to whatever account you think makes sense.

Cheers!

**Comment by megies** [comment]
I'm fine with either of these choices. A new organization might really be overkill. In principle I guess we could move it to obspy organization and set up rights there, but a downside might be that people expect obspy devs to maintain it.
So maybe best your personal or lab orga account.

**Comment by ogalanis** [comment]
Great. Can you, @krischer, as the owner transfer it to me for the reasons @megies stated? (although I am still open to other options and I don't see this transfer as an irreversible change)

**Comment by krischer** [comment]
Hi @ogalanis,

sorry for the delay. I just tried to transfer the repository to you but you already have a fork of the same name so I cannot do that. Could you either delete/rename that fork or create an organization for me to transfer the repository to?

Thanks!

**Comment by ogalanis** [comment]
Don't worry. Turns out that it's a good time for this.

I have renamed my fork. Can you try again?

**Comment by krischer** [comment]
Hmm - unfortunately it still does not work and Github complains:

grafik

I think you might have to fully delete your fork from github before I can transfer it. Or you first transfer the fork to another owner. Or you could create a new organization.

**Comment by ogalanis** [comment]
Okay. I have now deleted the fork.

**Comment by ogalanis** [comment]
It has been done! Thank you!

**Pull request closed without merging**
